package courseManagement;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DM
 */
public class UpdateCourse extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCourse


     */
    String s1 = "";
    String s2 = "";
    String s3 = "";
    String s4 = "";
    String s5 = "";
    String s6 = "";


    public UpdateCourse() {
        initComponents();
    }
boolean checksubject(String subject1, String subject2, String subject3, String subject4, String subject5, String subject6 ){
           String s = "Select Subject";
           if(subject1.equals(s) || subject2.equals(s)|| subject3.equals(s) || subject4.equals(s) || subject5.equals(s) || subject6.equals(s)){
                  return false;
           }
           return true;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subject2 = new javax.swing.JComboBox<>();
        subject3 = new javax.swing.JComboBox<>();
        subject4 = new javax.swing.JComboBox<>();
        subject5 = new javax.swing.JComboBox<>();
        subject6 = new javax.swing.JComboBox<>();
        subject1 = new javax.swing.JComboBox<>();
        addCourse = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subject2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        subject2.setToolTipText("");
        subject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject2ActionPerformed(evt);
            }
        });

        subject3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        subject3.setToolTipText("");
        subject3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject3ActionPerformed(evt);
            }
        });

        subject4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        subject4.setToolTipText("");
        subject4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject4ActionPerformed(evt);
            }
        });

        subject5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        subject5.setToolTipText("");
        subject5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject5ActionPerformed(evt);
            }
        });

        subject6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        subject6.setToolTipText("");
        subject6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject6ActionPerformed(evt);
            }
        });

        subject1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        subject1.setToolTipText("");
        subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1ActionPerformed(evt);
            }
        });

        addCourse.setText("Update Course");
        addCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Subject 1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Subject 2");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Subject 3");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Subject 4");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Subject 5");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Subject 6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subject6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addCourse)
                                    .addGap(18, 18, 18)
                                    .addComponent(back))
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGap(62, 62, 62)))
                    .addGap(68, 68, 68)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subject6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addCourse)
                        .addComponent(back))
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject2ActionPerformed
        // TODO add your handling code here:
        if(subject2.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please select the subject!");
            return;
        }
        s2 = subject2.getSelectedItem().toString();
        if(s2.equals(s5) || s2.equals(s4) || s2.equals(s3) || s2.equals(s6) || s2.equals(s1)){
            JOptionPane.showMessageDialog(null, "Please select another subject!");
            subject2.setSelectedIndex(0);
            return;
        }
    }//GEN-LAST:event_subject2ActionPerformed

    private void subject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject3ActionPerformed
        // TODO add your handling code here:
        if(subject3.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please select the subject!");
            return;
        }
        s3 = subject3.getSelectedItem().toString();
        if(s3.equals(s5) || s3.equals(s4) || s3.equals(s6) || s3.equals(s2) || s3.equals(s1)){
            JOptionPane.showMessageDialog(null, "Please select another subject!");
            subject3.setSelectedIndex(0);
            return;
        }
    }//GEN-LAST:event_subject3ActionPerformed

    private void subject4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject4ActionPerformed
        // TODO add your handling code here
        if(subject4.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please select the subject!");
            return;
        }
        s4 = subject4.getSelectedItem().toString();
        if(s4.equals(s5) || s4.equals(s6) || s4.equals(s3) || s4.equals(s2) || s4.equals(s1)){
            JOptionPane.showMessageDialog(null, "Please select another subject!");
            subject4.setSelectedIndex(0);
            return;
        }
    }//GEN-LAST:event_subject4ActionPerformed

    private void subject5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject5ActionPerformed
        // TODO add your handling code here:
        if(subject5.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please select the subject!");
            return;
        }
        s5 = subject5.getSelectedItem().toString();
        if(s5.equals(s6)||s5.equals(s4) || s5.equals(s3) || s5.equals(s2) || s5.equals(s1)){
            JOptionPane.showMessageDialog(null, "Please select another subject!");
            subject5.setSelectedIndex(0);
            return;
        }
    }//GEN-LAST:event_subject5ActionPerformed

    private void subject6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject6ActionPerformed
        // TODO add your handling code here:
        if(subject6.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please select the subject!");
            return;
        }
        s6 = subject6.getSelectedItem().toString();
        if(s6.equals(s5) || s6.equals(s4) || s6.equals(s3) || s6.equals(s2) || s6.equals(s1)){
            JOptionPane.showMessageDialog(null, "Please select another subject!");
            subject6.setSelectedIndex(0);
            return;
        }
    }//GEN-LAST:event_subject6ActionPerformed

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
        // TODO add your handling code here:
        if(subject1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please select the subject!");
            return;
        }
        s1 = subject1.getSelectedItem().toString();
        if(s1.equals(s5) || s1.equals(s4) || s1.equals(s6) || s1.equals(s2) || s1.equals(s3)){
            JOptionPane.showMessageDialog(null, "Please select another subject!");
            subject1.setSelectedIndex(0);
            return;
        }

    }//GEN-LAST:event_subject1ActionPerformed

    private void addCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseActionPerformed
        // TODO add your handling code here:
        String ss1 = subject1.getSelectedItem().toString();
        String ss2 = subject2.getSelectedItem().toString();
        String ss3 = subject3.getSelectedItem().toString();
        String ss4 = subject4.getSelectedItem().toString();
        String ss5 = subject5.getSelectedItem().toString();
        String ss6 = subject6.getSelectedItem().toString();
        if(!(checksubject(ss1, ss2, ss3, ss4, ss5, ss6))){
            JOptionPane.showMessageDialog(null, "Please select the subject!");
            return;
        }
        JOptionPane.showMessageDialog(null, "Course Successfully Updated");
        CourseTask ct = new CourseTask();
        ct.setVisible(true);
        this.dispose();

        //course
    }//GEN-LAST:event_addCourseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        CourseTask ct = new CourseTask();
        ct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourse;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> subject1;
    private javax.swing.JComboBox<String> subject2;
    private javax.swing.JComboBox<String> subject3;
    private javax.swing.JComboBox<String> subject4;
    private javax.swing.JComboBox<String> subject5;
    private javax.swing.JComboBox<String> subject6;
    // End of variables declaration//GEN-END:variables
}
