/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examManagement;
import courseManagement.CourseTask;
import javax.swing.JOptionPane;
import pojo.CourseData;
import pojo.ExamData;
import pojo.StudentData;
/**
 *
 * @author DM
 */
public class updateExam extends javax.swing.JFrame {

    /**
     * Creates new form updateExam
     */
    public updateExam() {
        initComponents();
    }
    boolean checkMarks(String sub1m, String sub2m, String sub3m, String sub4m, String sub5m, String sub6m, String tesId){
                   if(sub1m.isEmpty() ||sub2m.isEmpty() ||sub3m.isEmpty() ||sub4m.isEmpty() ||sub5m.isEmpty() ||sub6m.isEmpty() || tesId.isEmpty()){
                             return false;
                   }
                   return true;
   }
    private void clearFields(){
        jTextField2.setText("");
        sub1.setText("");
        sub1m.setText("");
        sub2.setText("");
        sub2m.setText("");
        sub3.setText("");
        sub3m.setText("");
        sub4.setText("");
        sub4m.setText("");
        sub5.setText("");
        sub5m.setText("");
        sub6.setText("");
        sub6m.setText("");
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sub1m = new javax.swing.JTextField();
        sub2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sub2m = new javax.swing.JTextField();
        sub3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sub3m = new javax.swing.JTextField();
        sub4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        examAdd = new javax.swing.JButton();
        examClear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        edataclass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        sub1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sub4m = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sub5m = new javax.swing.JTextField();
        sub5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sub6m = new javax.swing.JTextField();
        sub6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sub1m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1mActionPerformed(evt);
            }
        });
        sub1m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sub1mKeyPressed(evt);
            }
        });

        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Subject 2");

        jLabel8.setText("Subject 2 Marks");

        sub2m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sub2mKeyPressed(evt);
            }
        });

        sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Subject 3");

        jLabel10.setText("Subject 3 Marks");

        sub3m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3mActionPerformed(evt);
            }
        });
        sub3m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sub3mKeyPressed(evt);
            }
        });

        sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Subject 6");

        examAdd.setText("Update");
        examAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examAddActionPerformed(evt);
            }
        });

        examClear.setText("Clear");
        examClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examClearActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        edataclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edataclassActionPerformed(evt);
            }
        });

        jLabel3.setText("Class");

        jLabel4.setText("Test Id");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Subject 1");

        jLabel6.setText("Subject 1 Marks");

        jLabel11.setText("Subject 4");

        jLabel12.setText("Subject 4 Marks");

        sub4m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sub4mKeyPressed(evt);
            }
        });

        jLabel13.setText("Subject 5 Marks");

        sub5m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sub5mKeyPressed(evt);
            }
        });

        sub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub5ActionPerformed(evt);
            }
        });

        jLabel14.setText("Subject 5");

        jLabel15.setText("Subject 6 Marks");

        sub6m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub6mActionPerformed(evt);
            }
        });
        sub6m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sub6mKeyPressed(evt);
            }
        });

        sub6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(examAdd)
                            .addGap(37, 37, 37)
                            .addComponent(examClear)
                            .addGap(40, 40, 40)
                            .addComponent(back)
                            .addGap(77, 77, 77))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sub1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                .addComponent(sub1m)
                                .addComponent(edataclass)
                                .addComponent(jTextField2)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sub2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                .addComponent(sub2m)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sub5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                .addComponent(sub4m, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sub4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sub3m, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sub3)
                                .addComponent(sub5m)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sub6)
                                .addComponent(sub6m))))
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edataclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub1m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sub2m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sub3m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sub4m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sub5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sub5m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sub6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sub6m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(examAdd)
                        .addComponent(examClear)
                        .addComponent(back))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sub1mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1mActionPerformed

    private void sub1mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub1mKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();

        if(((c >= '0' && c<= '9') )|| c== 8){
            sub1m.setEditable(true);

        }else{
            sub1m.setEditable(false);
        }
    }//GEN-LAST:event_sub1mKeyPressed

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
        // TODO add your handling code here:
        sub2.setEditable(false);
    }//GEN-LAST:event_sub2ActionPerformed

    private void sub2mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub2mKeyPressed
        // TODO add your handling code here:

        Character c = evt.getKeyChar();

        if(((c >= '0' && c<= '9') )|| c== 8){
            sub2m.setEditable(true);

        }else{
            sub2m.setEditable(false);
        }
    }//GEN-LAST:event_sub2mKeyPressed

    private void sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3ActionPerformed
        // TODO add your handling code here:
        sub3.setEditable(false);
    }//GEN-LAST:event_sub3ActionPerformed

    private void sub3mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3mActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_sub3mActionPerformed

    private void sub3mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub3mKeyPressed
        // TODO add your handling code here
        Character c = evt.getKeyChar();

        if(((c >= '0' && c<= '9') )|| c== 8){
            sub3m.setEditable(true);

        }else{
            sub3m.setEditable(false);
        }
    }//GEN-LAST:event_sub3mKeyPressed

    private void sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub4ActionPerformed
        // TODO add your handling code here:
        sub4.setEditable(false);
    }//GEN-LAST:event_sub4ActionPerformed

    private void examAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examAddActionPerformed
        // TODO add your handling code here:

        ExamData examDetails = new ExamData();
        examDetails.setClassName(edataclass.getText());
        examDetails.setTestName(jTextField2.getText());
        examDetails.setSub1Name(sub1.getText());
        examDetails.setSub1Score(sub1m.getText());
        examDetails.setSub2Name(sub2.getText());
        examDetails.setSub2Score(sub2m.getText());
        examDetails.setSub3Name(sub3.getText());
        examDetails.setSub3Score(sub3m.getText());
        examDetails.setSub4Name(sub4.getText());
        examDetails.setSub4Score(sub4m.getText());
        examDetails.setSub5Name(sub5.getText());
        examDetails.setSub5Score(sub5m.getText());
        examDetails.setSub6Name(sub6.getText());
        examDetails.setSub6Score(sub6m.getText());

        if(!(checkMarks(sub1m.getText(),sub2m.getText(),sub3m.getText(),sub4m.getText(),sub5m.getText(),sub6m.getText(),jTextField2.getText()))){
            if(jTextField2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter Test ID!");
                return;
            }else{
                JOptionPane.showMessageDialog(null, "Please enter marks for all subjects!");
                return;

            }

        }
        if(ExamData.add(examDetails)){
            JOptionPane.showMessageDialog(this,"Successfully added exam details.");
            examMenu ct = new examMenu();
            ct.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(this,"Failed to add exam details, please try again later.");
            clearFields();
            return;
        }

    }//GEN-LAST:event_examAddActionPerformed

    private void examClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_examClearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        examMenu em = new examMenu();
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void edataclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edataclassActionPerformed
        // TODO add your handling code here:
        edataclass.setEditable(false);
    }//GEN-LAST:event_edataclassActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
        sub1.setEditable(false);
    }//GEN-LAST:event_sub1ActionPerformed

    private void sub4mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub4mKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();

        if(((c >= '0' && c<= '9') )|| c== 8){
            sub4m.setEditable(true);

        }else{
            sub4m.setEditable(false);
        }
    }//GEN-LAST:event_sub4mKeyPressed

    private void sub5mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub5mKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();

        if(((c >= '0' && c<= '9') )|| c== 8){
            sub5m.setEditable(true);

        }else{
            sub5m.setEditable(false);
        }
    }//GEN-LAST:event_sub5mKeyPressed

    private void sub5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub5ActionPerformed
        // TODO add your handling code here:
        sub5.setEditable(false);
    }//GEN-LAST:event_sub5ActionPerformed

    private void sub6mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub6mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub6mActionPerformed

    private void sub6mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub6mKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();

        if(((c >= '0' && c<= '9') )|| c== 8){
            sub6m.setEditable(true);

        }else{
            sub6m.setEditable(false);
        }
    }//GEN-LAST:event_sub6mKeyPressed

    private void sub6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub6ActionPerformed
        // TODO add your handling code here:
        sub6.setEditable(false);
    }//GEN-LAST:event_sub6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField edataclass;
    private javax.swing.JButton examAdd;
    private javax.swing.JButton examClear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField sub1;
    private javax.swing.JTextField sub1m;
    private javax.swing.JTextField sub2;
    private javax.swing.JTextField sub2m;
    private javax.swing.JTextField sub3;
    private javax.swing.JTextField sub3m;
    private javax.swing.JTextField sub4;
    private javax.swing.JTextField sub4m;
    private javax.swing.JTextField sub5;
    private javax.swing.JTextField sub5m;
    private javax.swing.JTextField sub6;
    private javax.swing.JTextField sub6m;
    // End of variables declaration//GEN-END:variables
}
